apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: swc-db-net-policy
  namespace: swc-app
spec:
  podSelector:
    matchLabels:
      app: swc-db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: swc-app
    - podSelector:
        matchLabels:
          app: swc-api
    ports:
      - port: 5432
        protocol: TCP
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: swc-app
    - podSelector:
        matchLabels:
          app: swc-db
    ports:
      - port: 5432
        protocol: TCP