apiVersion: v1
kind: PersistentVolume
metadata:
  name: swc-db-pv
  namespace: swc-app
  labels:
    type: local
    app: swc-db
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/postgres/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: swc-db-pv-claim
  namespace: swc-app
  labels:
    app: swc-db
spec:
  storageClassName: microk8s-hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi